#!/bin/sh
sxhkd &
xrandr --output eDP-1 --mode 1920x1080
xbacklightmon &
picom -b &
~/.config/polybar/launch.sh &
feh --no-fehbg --bg-fill ~/Pictures/background.png
wmname LG3D
export _JAVA_AWT_WM_NONREPARTENTING=1
export _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext-true'

bspc monitor eDP-1 -d 1 2 3 4

bspc config window_gap                  15
bspc config top_padding                 30
bspc config click_to_focus              button1
bspc config focus_follows_pointer       true
bspc config focused_border_color        \#ffffff
bspc config active_border_color         \#474645
bspc config normal_border_color         \#474645
bspc config split_ratio                 0.5

